# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-02 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=9999)),
                ('abstract', models.CharField(max_length=9999)),
                ('content', models.TextField()),
                ('image', models.FileField(upload_to='article_image')),
                ('insert_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('change_time', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
            ],
        ),
    ]
