# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-03 00:51
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20180603_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='abstract_image',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='\u6458\u8981\u56fe\u7247   '),
        ),
        migrations.AlterField(
            model_name='news',
            name='abstract',
            field=models.CharField(max_length=9999, verbose_name='\u6458\u8981'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='\u65b0\u95fb\u6b63\u6587    '),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=9999, verbose_name='\u65b0\u95fb\u6807\u9898'),
        ),
    ]
