# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-03 01:15
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20180603_0051'),
    ]

    operations = [
        migrations.CreateModel(
            name='company_news',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='\u65b0\u95fb\u7f16\u53f7')),
                ('title', models.CharField(max_length=9999, verbose_name='\u65b0\u95fb\u6807\u9898')),
                ('abstract', models.CharField(max_length=9999, verbose_name='\u6458\u8981')),
                ('abstract_image', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='\u6458\u8981\u56fe\u7247   ')),
                ('content', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='\u65b0\u95fb\u6b63\u6587    ')),
                ('insert_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('change_time', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
            ],
        ),
        migrations.CreateModel(
            name='industry_news',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='\u65b0\u95fb\u7f16\u53f7')),
                ('title', models.CharField(max_length=9999, verbose_name='\u65b0\u95fb\u6807\u9898')),
                ('abstract', models.CharField(max_length=9999, verbose_name='\u6458\u8981')),
                ('abstract_image', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='\u6458\u8981\u56fe\u7247   ')),
                ('content', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='\u65b0\u95fb\u6b63\u6587    ')),
                ('insert_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('change_time', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
            ],
        ),
        migrations.DeleteModel(
            name='news',
        ),
    ]
