# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-03 01:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20180603_0115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company_news',
            options={'verbose_name': '\u516c\u53f8\u65b0\u95fb', 'verbose_name_plural': '\u516c\u53f8\u65b0\u95fb'},
        ),
        migrations.AlterModelOptions(
            name='industry_news',
            options={'verbose_name': '\u884c\u4e1a\u65b0\u95fb', 'verbose_name_plural': '\u884c\u4e1a\u65b0\u95fb'},
        ),
    ]
