# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-23 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20180603_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_news',
            name='abstract_image',
            field=models.ImageField(upload_to='img'),
        ),
        migrations.AlterField(
            model_name='industry_news',
            name='abstract_image',
            field=models.ImageField(upload_to='img'),
        ),
    ]
