# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-23 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20180623_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_news',
            name='abstract_image',
            field=models.ImageField(upload_to='img', verbose_name='\u6458\u8981\u56fe\u7247'),
        ),
        migrations.AlterField(
            model_name='industry_news',
            name='abstract_image',
            field=models.ImageField(upload_to='img', verbose_name='\u6458\u8981\u56fe\u7247'),
        ),
    ]
