# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-23 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product_center',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='\u4ea7\u54c1\u7f16\u53f7')),
                ('img', models.ImageField(upload_to='img')),
                ('name', models.CharField(max_length=20, verbose_name='\u4ea7\u54c1\u540d\u79f0')),
                ('type', models.IntegerField(choices=[(1, '\u9c9c\u6d3b\u4ea7\u54c1'), (2, '\u51b7\u51bb\u4ea7\u54c1'), (3, '\u52a0\u5de5\u4ea7\u54c1'), (4, '\u7cbe\u54c1\u793c\u76d2')])),
                ('insert_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('change_time', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u4ea7\u54c1\u4e2d\u5fc3',
                'verbose_name_plural': '\u4ea7\u54c1\u4e2d\u5fc3',
            },
        ),
    ]
